@echo off

echo Downloading LibreOffice...
curl -L -o LibreOffice.exe https://download.documentfoundation.org/libreoffice/stable/7.2.6/win/x86_64/LibreOffice_7.2.6_Win_x64.msi
echo Installing LibreOffice...
start /wait LibreOffice.exe /passive

echo Downloading GIMP...
curl -L -o GIMP.exe https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.28-x64-1.exe
echo Installing GIMP...
start /wait GIMP.exe /S

echo Downloading VLC Media Player...
curl -L -o VLC.exe https://get.videolan.org/vlc/3.0.16/win64/vlc-3.0.16-win64.exe
echo Installing VLC Media Player...
start /wait VLC.exe /L=1033 /S

echo Downloading Audacity...
curl -L -o Audacity.exe https://www.gyan.dev/ffmpeg/builds/audacity/audacity-3.1.3/audacity-3.1.3-win-x64.exe
echo Installing Audacity...
start /wait Audacity.exe /S

echo Downloading Firefox...
curl -L -o Firefox.exe https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US
echo Installing Firefox...
start /wait Firefox.exe /S

echo Downloading Thunderbird...
curl -L -o Thunderbird.exe https://download.mozilla.org/?product=thunderbird-latest-ssl&os=win64&lang=en-US
echo Installing Thunderbird...
start /wait Thunderbird.exe /S

echo Downloading 7-Zip...
curl -L -o 7zip.exe https://www.7-zip.org/a/7z2106-x64.exe
echo Installing 7-Zip...
start /wait 7zip.exe /S

echo Downloading Notepad++...
curl -L -o Notepad++.exe https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.2/npp.8.1.2.Installer.x64.exe
echo Installing Notepad++...
start /wait Notepad++.exe /S

echo Downloading Blender...
curl -L -o Blender.exe https://mirror.clarkson.edu/blender/release/Blender2.93/blender-2.93.5-windows-x64.zip
echo Installing Blender...
unzip -q Blender.exe -d C:\Program Files\Blender

echo Downloading Inkscape...
curl -L -o Inkscape.exe https://inkscape.org/gallery/item/50448/Inkscape-1.1-x64.msi
echo Installing Inkscape...
start /wait Inkscape.exe /qn
